### ISSUE TITLE
Issue with more than one dropdown

### ISSUE THREAD

**Issue by ihmunro** [BijeshNair/NIDropDown#10]
Hi There

Great control.

I have four dropdowns listed, the 4th one as example, you have to click it 3 additional times in order to get to the 4th listing.

Same goes for 3, but one less selection, then 2 etc.

Any help would be appreciated.

Iain

**Comment by BijeshNair** [comment]
Hi, I've updated the repo to handle this :)
I know it's tooooo late and you might not need it anymore. 

Thanks for pointing this out.
