### ISSUE TITLE
Hi ,I have tried with NIDropDown , list is display but touch method "niDropDownDelegateMethod" is not called Note :I have set delegate there,at the top for dropdown object

### ISSUE THREAD

**Issue by andela-hchukwu** [BijeshNair/NIDropDown#20]

**Comment by BijeshNair** [comment]
Hi, Have you gone through the sample app?
Check NIViewController.m for the implementation

**Comment by BijeshNair** [comment]
I've update the repository. Kindly take a look...

**Comment by andela-hchukwu** [comment]
To be clear I have just one drop down but I can't click on it after it is displayed

**Comment by andela-hchukwu** [comment]
Still happening, I'll be grateful if this can be resolved thanks

**Comment by BijeshNair** [comment]
Happy to know it's resolved.
Thank you!
