### ISSUE TITLE
Drop down menu showing behind other UI elements.

### ISSUE THREAD

**Issue by HussainSatham** [BijeshNair/NIDropDown#21]
I have my button inside stackview and tried clicking it, drop down menu shows behind the other UI elements I have below the button. Any fix?

Thanks,
Rahman.

**Comment by BijeshNair** [comment]
Hi, can you attach a screenshot of this?
Or you can send it to bijesh4@gmail.com

**Comment by HussainSatham** [comment]
Hi Bijesh, I was having the button inside a stack view that's the reason it was showing behind the other UI elements. I removed the stackview and it's working fine. Thanks.
